### ISSUE TITLE
Question: Is it possible for a MacOs app to communicate with an iOS app inside the simulator?

### ISSUE THREAD

**Issue by patchthecode** [OpenEmu/OpenEmuXPCCommunicator#5]
Is it possible for a **MacOs** app running on the Mac computer to communicate with an **iOS** app running inside simulator?

Both apps are on the same machine.
The apps have no sandbox.

**Comment by rudyrichter** [comment]
No.  The API one would have to use is marked as unavailable by Apple.

`- (instancetype)initWithMachServiceName:(NSString *)name NS_DESIGNATED_INITIALIZER API_UNAVAILABLE(ios, watchos, tvos);`
